nelmio_api_doc:
    documentation:
        info:
            title: Purchase Plan API
            description: Приложение для создания плана закупок!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
